### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by bkdev98** [targeek/targeek-image-server#1]
I don't know how to use huhu.

**Comment by duongdev** [comment]
# Installation
```
yarn install
```

# Development
```
yarn start
```

# Production
```
yarn build
yarn start:production
```

This project is WIP. We will update the README ASAP. If possible, you can make a PR to add a README. We will very appreciated.

**Comment by duongdev** [comment]
@bkdev98 I have added a simple README.md to let people know how to start with this project. Please check and feel free to make it better.
